# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_validator/proto/grpc_ip/ip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#ip_validator/proto/grpc_ip/ip.proto\"1\n\tIPRequest\x12\x11\n\tipAddress\x18\x01 \x01(\t\x12\x11\n\tcountries\x18\x02 \x03(\t\"\x1b\n\nIPResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\x36\n\x0bIPValidator\x12\'\n\nValidateIP\x12\n.IPRequest\x1a\x0b.IPResponse\"\x00\x62\x06proto3')

_IPREQUEST = DESCRIPTOR.message_types_by_name['IPRequest']
_IPRESPONSE = DESCRIPTOR.message_types_by_name['IPResponse']
IPRequest = _reflection.GeneratedProtocolMessageType('IPRequest', (_message.Message,), {
    'DESCRIPTOR': _IPREQUEST,
    '__module__': 'ip_validator.proto.grpc_ip.ip_pb2'
    # @@protoc_insertion_point(class_scope:IPRequest)
})
_sym_db.RegisterMessage(IPRequest)

IPResponse = _reflection.GeneratedProtocolMessageType('IPResponse', (_message.Message,), {
    'DESCRIPTOR': _IPRESPONSE,
    '__module__': 'ip_validator.proto.grpc_ip.ip_pb2'
    # @@protoc_insertion_point(class_scope:IPResponse)
})
_sym_db.RegisterMessage(IPResponse)

_IPVALIDATOR = DESCRIPTOR.services_by_name['IPValidator']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _IPREQUEST._serialized_start = 39
    _IPREQUEST._serialized_end = 88
    _IPRESPONSE._serialized_start = 90
    _IPRESPONSE._serialized_end = 117
    _IPVALIDATOR._serialized_start = 119
    _IPVALIDATOR._serialized_end = 173
# @@protoc_insertion_point(module_scope)
