# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ip_pb2 as ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2


class IPValidatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateIP = channel.unary_unary(
                '/IPValidator/ValidateIP',
                request_serializer=ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPRequest.SerializeToString,
                response_deserializer=ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPResponse.FromString,
                )


class IPValidatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPValidatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateIP': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateIP,
                    request_deserializer=ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPRequest.FromString,
                    response_serializer=ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IPValidator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IPValidator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IPValidator/ValidateIP',
            ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPRequest.SerializeToString,
            ip__validator_dot_proto_dot_grpc__ip_dot_ip__pb2.IPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
